# Generated by Django 3.0 on 2020-01-05 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_goodsimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='create_date',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='goods',
            old_name='update_date',
            new_name='update_time',
        ),
        migrations.RenameField(
            model_name='goodsimage',
            old_name='create_date',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='goodsimage',
            old_name='update_date',
            new_name='update_time',
        ),
        migrations.RenameField(
            model_name='goodssku',
            old_name='create_date',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='goodssku',
            old_name='update_date',
            new_name='update_time',
        ),
        migrations.RenameField(
            model_name='goodstype',
            old_name='create_date',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='goodstype',
            old_name='update_date',
            new_name='update_time',
        ),
        migrations.RenameField(
            model_name='indexgoodsbanner',
            old_name='create_date',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='indexgoodsbanner',
            old_name='update_date',
            new_name='update_time',
        ),
        migrations.RenameField(
            model_name='indexpromotionbanner',
            old_name='create_date',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='indexpromotionbanner',
            old_name='update_date',
            new_name='update_time',
        ),
        migrations.RenameField(
            model_name='indextypegoodsbanner',
            old_name='create_date',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='indextypegoodsbanner',
            old_name='update_date',
            new_name='update_time',
        ),
    ]
