# Generated by Django 3.0 on 2020-01-05 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='create_date',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='update_date',
            new_name='update_time',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='create_date',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='update_date',
            new_name='update_time',
        ),
    ]
