# Generated by Django 3.0 on 2020-01-05 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200105_2113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordergoods',
            old_name='create_date',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='ordergoods',
            old_name='update_date',
            new_name='update_time',
        ),
        migrations.RenameField(
            model_name='orderinfo',
            old_name='create_date',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='orderinfo',
            old_name='update_date',
            new_name='update_time',
        ),
    ]
